[package]
name = "impl_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "graph_grid"
path = "src/graph/graph_grid.rs"

[dependencies]
