[package]
name = "neet_code_all"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

## Array & Hashing

[[bin]]
name = "concatenation_of_array"
path = "src/array_hash/concatenation_of_array.rs"

[[bin]]
name = "replace_elements_with_greatest_right"
path = "src/array_hash/replace_elements_with_greatest_right.rs"

[[bin]]
name = "is_subsequence"
path = "src/array_hash/is_subsequence.rs"

[[bin]]
name = "len_of_last_word"
path = "src/array_hash/len_of_last_word.rs"

[[bin]]
name = "longest_common_prefix"
path = "src/array_hash/longest_common_prefix.rs"

[[bin]]
name = "pascal_triangle"
path = "src/array_hash/pascal_triangle.rs"


[dependencies]
