[package]
name = "neet_code_all"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "concatenation_of_array"
path = "src/array_hash/concatenation_of_array.rs"

[[bin]]
name = "replace_elements_with_greatest_right"
path = "src/array_hash/replace_elements_with_greatest_right.rs"

[[bin]]
name = "is_subsequence"
path = "src/array_hash/is_subsequence.rs"

[dependencies]
