[package]
name = "neet_code_150"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

## Arrays & Hashing 
[[bin]]
name = "contains_duplicate"
path = "src/array_hash/contains_duplicate.rs"

[[bin]]
name = "valid_anagram"
path = "src/array_hash/valid_anagram.rs"

[[bin]]
name = "two_sum"
path = "src/array_hash/two_sum.rs"

[[bin]]
name = "group_anagram"
path = "src/array_hash/group_anagram.rs"

[[bin]]
name = "top_k_freq"
path = "src/array_hash/top_k_freq.rs"

[[bin]]
name = "prod_array_except"
path = "src/array_hash/product_of_array_except_self.rs"

[[bin]]
name = "valid_sudoku"
path = "src/array_hash/valid_sudoku.rs"

[[bin]]
name = "longest_consecutive"
path = "src/array_hash/longest_consecutive_sequence.rs"

## Two & Pointers 
[[bin]]
name = "valid_palindrome"
path = "src/two_pointers/valid_palindrome.rs"

[[bin]]
name = "two_sum_2"
path = "src/two_pointers/two_sum_2.rs"

[[bin]]
name = "tree_sum"
path = "src/two_pointers/tree_sum.rs"

[[bin]]
name = "continer_water"
path = "src/two_pointers/continer_with_most_water.rs"

## Sliding Window
[[bin]]
name = "buy_sell"
path = "src/sliding_window/best_time_buy_sell.rs" 

[[bin]]
name = "longest_substr"
path = "src/sliding_window/longest_substring_no_repeat.rs"

[[bin]]
name = "longest_repeating"
path = "src/sliding_window/longest_repeating_char.rs"

[[bin]]
name = "permutation_str"
path = "src/sliding_window/permutation_in_str.rs"

## Stack
[[bin]]
name = "valid_par"
path = "src/stack/valid_par.rs"

[[bin]]
name = "min_stack"
path = "src/stack/min_stack.rs"

[[bin]]
name = "rev_polish"
path = "src/stack/rev_polish.rs"

## Binary Search
[[bin]]
name = "bin_search"
path = "src/binary_search/bin_search.rs"

[[bin]]
name = "search_2dmat"
path = "src/binary_search/search_2dmatrix.rs"

[[bin]]
name = "koko_banana"
path = "src/binary_search/koko_banana.rs"

[[bin]]
name = "sorted_rot"
path = "src/binary_search/minimum_rotated_sorted_array.rs"

[[bin]]
name = "sorted_rot_search"
path = "src/binary_search/search_rotated_sorted_array.rs"

[[bin]]
name = "timebase_key"
path = "src/binary_search/timebase_key.rs"

# appendix
[[bin]]
name = "hash_map"
path = "src/appendix/hash_map.rs"


[dependencies]
