[package]
name = "neet_code_150"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "contains_duplicate"
path = "src/array_hash/contains_duplicate.rs"

[[bin]]
name = "valid_anagram"
path = "src/array_hash/valid_anagram.rs"

[[bin]]
name = "two_sum"
path = "src/array_hash/two_sum.rs"

[[bin]]
name = "group_anagram"
path = "src/array_hash/group_anagram.rs"

[[bin]]
name = "top_k_freq"
path = "src/array_hash/top_k_freq.rs"

# appendix
[[bin]]
name = "hash_map"
path = "src/appendix/hash_map.rs"

[dependencies]
